name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  release:    
    needs: build    
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest    
    permissions:
      contents: write      
    steps:      
      - name: Checkout
        uses: actions/checkout@v2     
      - name: Get version from tag
        id: tag_name
        run: |          
          GHREF=${GITHUB_REF#refs/tags/}; echo ::set-output name=current_version::${GHREF%-*}
        shell: bash
      - name: Build Release Assets
        id: build_release_assets
        run: |
          echo "this is a test" > scripts/cpack/asset.test
        shell: bash
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:          
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.changelog_reader.outputs.changes }}          
          token: ${{ secrets.GITHUB_TOKEN }}          
          prerelease: contains(steps.tag_name.outputs.current_version, '-rc')
          draft: true
          files: |
            scripts/cpack/asset.deb
            scripts/cpack/asset.rpm    
            scripts/cpack/asset.test        
